# Set global configuration arguments
cask_args appdir: "~/Applications"

# Taps
tap "caskroom/cask"
tap "caskroom/fonts"
tap "caskroom/versions"
tap "homebrew/bundle"
tap "homebrew/core"

# Cask dependencies
brew "mas"
cask "java"
cask "xquartz"

# Shells
# Note: Don't forget to add shells to `/etc/shells` before running `chsh`.
brew "bash"
brew "zsh"

# CLI utilities
brew "pcre"
brew "git", args: ["with-blk-sha1", "with-gettext", "with-pcre", "with-persistent-https"]
brew "wget"
brew "curl"
brew "autojump"
brew "chisel"
brew "fzf"
brew "fd" 
brew "tree"
brew "highlight"

# Install GUI applications
cask "alfred"
cask "atom"
cask "banktivity"
cask "carbon-copy-cloner"
cask "dropbox"
cask "fantastical"
cask "gifs"
cask "goofy"
cask "hipchat"
cask "istat-menus"
cask "kaleidoscope"
cask "little-snitch"
cask "monodraw"
cask "skype"
cask "soulver"
cask "suspicious-package"
cask "sublime-text"
cask "the-unarchiver"
cask "tower"
cask "tunnelbear"
cask "transmission"
cask "transmit"
cask "unrarx"
cask "vlc"
cask "viber"

# Browsers
cask "google-chrome"
cask "google-chrome-canary"
cask "firefox"
cask "firefox-nightly"

# Virtulization applications
cask "parallels-desktop"

# Preference Panes
cask "hosts"

# Fonts
cask "font-hack"
cask "font-fira-mono"

# MAS applications
# Get a list of installed MAS apps with:
# `brew bundle dump --file=- | egrep ^mas`
mas "1Blocker", id: 1107421413
mas "xScope", id: 889428659
mas "Deckset", id: 847496013
mas "Pixelmator", id:407963104
mas "CARROT Weather", id: 993487541
mas "Tweetbot", id: 557168941
mas "Twitterrific", id: 1289378661
mas "Reeder", id: 880001334
mas "Deliveries", id: 924726344
mas "DaisyDisk", id: 411643860
mas "Moom",id: 419330170
mas "Sequence Diagram", id: 1195426709

# Apple MAS applications
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
