#!/usr/local/bin/bash

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until script has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Install all available updates
#sudo softwareupdate -ia --verbose

declare -a INSTALLERS=(
  xcode # XCode __must__ be installed before Homebrew
  homebrew # Homebrew __must__ be installed before other tools
  shells
)

# Sources all the preference files
for file in "${INSTALLERS[@]}"; do
  file="installers/${file}.sh"
  [ -r "$file" ] && [ -f "$file" ] && source "$file"
done;
